name: PreRelease

on: 
  workflow_dispatch:
    inputs:
      semanticVersion:
        description: 'Semantic Version [major | minor | patch ]'
        required: true
        default: 'patch'

jobs:
  Publish:
    name: PreRelease
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Extract branch name
        run: echo "Deploying to production server on branch $GITHUB_REF"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: aaa
        run: echo running on branch ${GITHUB_REF##*/}
      - name: bbbb
        run: echo running on branch ${steps.extract_branch.outputs.branch}
